require 'yaml'
require 'date'
require 'ffaker'
require_relative '../../storage/database/db/db_utils.rb'
require_relative '../exceptions/exceptions.rb'
require_relative '../modules/validating.rb'

require_relative '../author.rb'
require_relative '../reader.rb'
require_relative '../order.rb'
require_relative '../book.rb'
require_relative '../library.rb'
require_relative '../statistic.rb'
require_relative '../output.rb'
require_relative '../services/filling.rb'
