require 'yaml'
require 'date'
require 'ffaker'
require_relative '../modules/request.rb'
require_relative '../modules/validate.rb'

require_relative '../author.rb'
require_relative '../reader.rb'
require_relative '../order.rb'
require_relative '../book.rb'
require_relative '../library.rb'
require_relative '../statistic.rb'
require_relative '../statistic.rb'
require_relative '../output.rb'
